/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author aleja
 */
public class Actualizar_EliminarS2 extends javax.swing.JPanel {

    /**
     * Creates new form Actualizar_EliminarS2
     */
    public Actualizar_EliminarS2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextNombre = new javax.swing.JTextField();
        TextApeP = new javax.swing.JTextField();
        TextApeM = new javax.swing.JTextField();
        TextDomicilio = new javax.swing.JTextField();
        TextFechaNac = new javax.swing.JTextField();
        TextTelefono = new javax.swing.JTextField();
        ButtonDelete = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        ComboSede = new javax.swing.JComboBox<>();
        ComboCuota = new javax.swing.JComboBox<>();
        TextCuentaBan = new javax.swing.JTextField();
        TextFechaPag = new javax.swing.JTextField();
        LabelNombre = new javax.swing.JLabel();
        LabelApeP = new javax.swing.JLabel();
        LabelApM = new javax.swing.JLabel();
        LabelDoc = new javax.swing.JLabel();
        LableFechaN = new javax.swing.JLabel();
        LabelTel = new javax.swing.JLabel();
        LableCuentBan = new javax.swing.JLabel();
        FechaPag = new javax.swing.JLabel();
        LabelSede = new javax.swing.JLabel();
        LabelCuota = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 101, 175, -1));
        add(TextApeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 135, 175, -1));
        add(TextApeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 164, 175, -1));
        add(TextDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 192, 175, -1));
        add(TextFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 220, 175, -1));
        add(TextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 249, 175, -1));

        ButtonDelete.setBackground(new java.awt.Color(0, 51, 102));
        ButtonDelete.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        ButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDelete.setText("Eliminar");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });
        add(ButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 83, -1));

        ButtonUpdate.setBackground(new java.awt.Color(0, 51, 102));
        ButtonUpdate.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        ButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        ButtonUpdate.setText("Actualizar");
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });
        add(ButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        add(ComboSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 368, -1, -1));

        add(ComboCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 399, -1, -1));
        add(TextCuentaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 277, 176, -1));
        add(TextFechaPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 305, 176, -1));

        LabelNombre.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        LabelNombre.setText("Nombre:");
        add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 106, -1, -1));

        LabelApeP.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        LabelApeP.setText("Apellido Paterno:");
        add(LabelApeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 140, -1, -1));

        LabelApM.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        LabelApM.setText("Apellido Materno:");
        add(LabelApM, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 169, -1, -1));

        LabelDoc.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        LabelDoc.setText("Domicilio:");
        add(LabelDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 197, -1, -1));

        LableFechaN.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        LableFechaN.setText("Fecha Nacimiento:");
        add(LableFechaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 225, -1, -1));

        LabelTel.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        LabelTel.setText("Telefono:");
        add(LabelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 254, -1, -1));

        LableCuentBan.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        LableCuentBan.setText("Cuenta Bancaria:");
        add(LableCuentBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 285, -1, -1));

        FechaPag.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        FechaPag.setText("Fecha Pago:");
        add(FechaPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 310, -1, -1));

        LabelSede.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        LabelSede.setText("Sede:");
        add(LabelSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 373, -1, -1));

        LabelCuota.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        LabelCuota.setText("Cuota:");
        add(LabelCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 404, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, 115, 274));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actualizar Socios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel1)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
//        ms.setNombre(TextNombre.getText());
//        ms.setApellidoP(TextApeP.getText());
//        ms.setApellidoM(TextApeM.getText());
//        ms.setDomicilio(TextDomicilio.getText());
//        ms.setFechaNac(TextFechaNac.getText());
//        ms.setTelefono(TextTelefono.getText());
//        ms.setCuentaBnacaria(TextCuentaBan.getText());
//        ms.setFechPago(TextFechaPag.getText());
//        ms.setIdSede((String) ComboSede.getSelectedItem());
//        String consultan = "select idSede from sede where ciudad ="+"'"+ms.getIdSede()+"'";
//        int id2 = cs.llamarId(consultan);
//        ms.setTipoCuota((String) ComboCuota.getSelectedItem());
//        int c1 = ComboSede.getSelectedIndex();
//        int c2 = ComboCuota.getSelectedIndex();
//        int id = 0;
//            if(mapa.containsKey(ms.getNombre())){
//                id = mapa.get(ms.getNombre());
//                System.out.println(id);
//            }
//        cs.actSocio(ms.getNombre(), ms.getApellidoP(), ms.getApellidoM(), ms.getDomicilio(), ms.getFechaNac(), ms.getTelefono(), ms.getCuentaBnacaria(), ms.getFechPago(), id2, ms.getTipoCuota(), id);
//        TextNombre.setText("");
//        TextApeP.setText("");
//        TextApeM.setText("");
//        TextDomicilio.setText("");
//        TextFechaNac.setText("");
//        TextTelefono.setText("");
//        TextCuentaBan.setText("");
//        TextFechaPag.setText("");
//        ComboSede.setSelectedIndex(c1);
//        ComboCuota.setSelectedIndex(c2);
//        this.repaint();
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
//        ms.setNombre(TextNombre.getText());
//        ms.setApellidoP(TextApeP.getText());
//        ms.setApellidoM(TextApeM.getText());
//        ms.setDomicilio(TextDomicilio.getText());
//        ms.setFechaNac(TextFechaNac.getText());
//        ms.setTelefono(TextTelefono.getText());
//        ms.setCuentaBnacaria(TextCuentaBan.getText());
//        ms.setFechPago(TextFechaPag.getText());
//        ms.setIdSede((String) ComboSede.getSelectedItem());
//        String consultan = "select idSede from sede where ciudad ="+"'"+ms.getIdSede()+"'";
//        int id2 = cs.llamarId(consultan);
//        ms.setTipoCuota((String) ComboCuota.getSelectedItem());
//        int c1 = ComboSede.getSelectedIndex();
//        int c2 = ComboCuota.getSelectedIndex();
//        int id = 0;
//        if(mapa.containsKey(ms.getNombre())){
//            id = mapa.get(ms.getNombre());
//            System.out.println(id);
//        }
//        cs.actSocio(ms.getNombre(), ms.getApellidoP(), ms.getApellidoM(), ms.getDomicilio(), ms.getFechaNac(), ms.getTelefono(), ms.getCuentaBnacaria(), ms.getFechPago(), id2, ms.getTipoCuota(), id);
//        TextNombre.setText("");
//        TextApeP.setText("");
//        TextApeM.setText("");
//        TextDomicilio.setText("");
//        TextFechaNac.setText("");
//        TextTelefono.setText("");
//        TextCuentaBan.setText("");
//        TextFechaPag.setText("");
//        ComboSede.setSelectedIndex(c1);
//        ComboCuota.setSelectedIndex(c2);
//        this.repaint();
    }//GEN-LAST:event_ButtonUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JComboBox<String> ComboCuota;
    private javax.swing.JComboBox<String> ComboSede;
    private javax.swing.JLabel FechaPag;
    private javax.swing.JLabel LabelApM;
    private javax.swing.JLabel LabelApeP;
    private javax.swing.JLabel LabelCuota;
    private javax.swing.JLabel LabelDoc;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelSede;
    private javax.swing.JLabel LabelTel;
    private javax.swing.JLabel LableCuentBan;
    private javax.swing.JLabel LableFechaN;
    private javax.swing.JTextField TextApeM;
    private javax.swing.JTextField TextApeP;
    private javax.swing.JTextField TextCuentaBan;
    private javax.swing.JTextField TextDomicilio;
    private javax.swing.JTextField TextFechaNac;
    private javax.swing.JTextField TextFechaPag;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
